name: Update mirrors
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
    
jobs:
  update-bukkit:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        run: |
          git clone https://hub.spigotmc.org/stash/scm/spigot/bukkit.git
        
      - name: Push to mirror
        run: |
          cd bukkit
          git remote add mirror https://Weredime:$GH_PAT@github.com/Weredime/Bukkit.git
          git push --all --quiet mirror
        env:
          GH_PAT: ${{ env.GH_PAT }}